Update godbus dependency to latest
Coder fails to build [1] on FreeBSD:

transport_unix.go:52:10: cannot use t (variable of type *unixTransport) as type transport in return statement:
        *unixTransport does not implement transport (missing SendNullByte method)

Update godbus dependency to latest, post upstream PR #332 [2] via #237

Fixes: #4516

[1] https://github.com/coder/coder/issues/4516
[2] https://github.com/godbus/dbus/pull/332
[3] https://github.com/godbus/dbus/pull/237