fix(cli): show error instead of help for unsupported subcommands (#10760)
The coder CLI quietly accepts any subcommand arguments and silently swallows them.

Currently:
❯ coder idontexist | head -n5
coder v2.3.3+e491217

USAGE:
  coder [global-flags] <subcommand>

Now help output will not be show but users will be given
the command for the help output.

❯ coder idontexist
Encountered an error running "coder", see "coder --help" for more information
error: unrecognized subcommand "idontexist"

❯ coder iexistbut idontexist
Encountered an error running "coder iexistbut", see "coder iexistbut --help" for more information
unrecognized subcommand "idontexist"